### ISSUE TITLE
Zadaci_12nov2021

### ISSUE THREAD

**Issue by dk1629** [dajuric/git-project-lipik#1]
Pozdrav Darko,
šaljem par komentara: 

"25. Zašto:
def sortJsonArray():
    jsonArr = json.loads(jsonStrB) 

a ne: 
def sortJsonArray(js):
    jsonArr = json.loads(js) 
? 

--> gledam u smjeru: imam main.py skriptu i sad pozivam sortJsonArray funkciju (from script_name import sortJsonArray i onda call) - hardcodean mi je neki json tamo, a ja mu želim dati neki novi 

27. Tinder.txt --> jesi htio imati 3 \s charactera prije opisa? Kod kreiranja csv-a bi neka praksa bila staviti neki delimiter koji si provjerio da se ne pojavljuje (da se ne brejka poslije) 
- Pogledaj što radi os.path.abspath(__file__) i koja je razlika u odnosu na os.path.abspath(os.getcwd()) 
- Što ako netko pokrene skriptu u terminalu kod sebe u ../Projects$ directoryju, a skripta se nalazi u ../Projects/xxdatum/zadaci$ ? 

--> generalno, jako impresivno"

**Comment by dajuric** [comment]
Bok,

hvala na komentaru. To mi znači.

25 -> zaboravio. Žurio se.
27 ->hvala na komentaru. Pogledat ću to detaljnije.

Darko
